# Learn more about Makefile: https://makefiletutorial.com

# Inside API folder in terminal, type: make run
run:
	dotnet watch --no-hot-reload

# Note: Adding .PHONY to a target will prevent Make from confusing the phony target with a file name.
.PHONY: run